version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command:
              mvn verify sonar:sonar -Dsonar.projectKey=luchotex_personal-account -Dsonar.organization=unosquarelk -Dsonar.host.url=https://sonarcloud.io

      - run:
          name: Save test results
          command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
