version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command:
              -mvn verify sonar:sonar -Dsonar.projectKey=luchotex_personal-account -Dsonar.organization=unosquarelk -Dsonar.host.url=https://sonarcloud.io
              -mkdir -p test-results
      - store_test_results:
          path: test-results


workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
