version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -Dsonar.projectKey=luchotex_personal-account -Dsonar.organization=unosquarelk -Dsonar.host.url=https://sonarcloud.io
          environment:
              JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit


workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
